#!/usr/bin/env bash
# Copy the paper and the slides into public/website, the site published to
# GitHub Pages by .github/workflows/website.yml:
#
#   index.html, style.css   checked in
#   paper.pdf               our own build, from paper/paper.pdf
#   paper-acm.pdf           the ACM version of record, from paper/paper-acm.pdf
#   presentation/           copied here from presentation-oopsla/
#   mechanization/          generated by mechanization/gendoc.sh
#
# Everything copied or generated into website/ is gitignored.
set -euo pipefail

cd "$(dirname "$0")"

out=website

# paper.pdf is our own build, so that the plain name keeps tracking the latest
# corrections. The ACM version of record, which is frozen and carries the
# artifact evaluation badges, ships beside it under its own name.
cp paper/paper.pdf "$out/paper.pdf"
cp paper/paper-acm.pdf "$out/paper-acm.pdf"

# The reveal.js slides need their siblings (lib/, custom.css, the images), so
# the whole directory ships; presentation.html becomes the directory index so
# that the link is just "presentation/".
rm -rf "$out/presentation"
mkdir -p "$out/presentation"
cp -R presentation-oopsla/. "$out/presentation"
mv "$out/presentation/presentation.html" "$out/presentation/index.html"
rm -f "$out/presentation/Makefile" "$out/presentation/presentation.md"
find "$out/presentation" -name .DS_Store -delete

echo "Paper and slides copied into $(cd "$out" && pwd)"
echo "Run mechanization/gendoc.sh for the Rocq documentation."
